
    upstream frontend_service { 
        # TODO: указать имя frontend-сервиса из docker-compose.yml и его внутренний порт
        # пример: server frontend:80;
        server frontend:3000;
    }

    upstream backend_service {
        # TODO: указать имя backend-сервиса из docker-compose.yml и его внутренний порт
        # пример: server backend:8000;
        server backend:8000;
    }

    server {
        listen 80;

        location / {
            # TODO: прокинуть запросы на frontend_service
            proxy_pass http://frontend_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/ {
            # TODO: прокинуть запросы на backend_service
            proxy_pass http://backend_service;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    
}
